name: Publish Package to npmjs
on:
  push:
    branches:
      - 'main'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn install
      - run: yarn build
      - run: yarn test:ci
      - run: yarn prepub
      - run: yarn e2e
      - run: yarn pub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Get tag
        run: |
          echo "version=v$(npm pkg get version | tr -d '\"')" >> $GITHUB_OUTPUT
      - name: Tag the commit
        run: |
          next_version=${{ steps.get_tag.outputs.version }}
          git tag -a "$next_version" -m "V $next_version"
          git push --follow-tags
